package car.gui;

import car.app.CarManager;
import car.data.Car;
import javax.swing.JOptionPane;

/**
 *
 * @author Prof. Werner Burkard
 */
public class CarGuiExample extends javax.swing.JFrame
{

    CarManager carManager;  // the manager of all cars

    /**
     * Creates new form FirstGUISS20
     */
    public CarGuiExample()
    {
        // get the Car Manager first
        carManager = CarManager.getInstance();
        // Read all the cars we already have saved to disk
        Car.readCars();
        // Let the carManager create some cars for test purposes, if ...
        // ... there are no cars yet
        if (Car.getCarList().isEmpty())
        {
            carManager.createSomeCars();
        }
        initComponents();
        this.setLocationRelativeTo(null); //Center JFrame on screen
        carManagerGui.pack();
        carManagerGui.setLocationRelativeTo(this); // position Dialog at JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carManagerGui = new javax.swing.JDialog();
        jButtonDone = new javax.swing.JButton();
        jButtonAddCar = new javax.swing.JButton();
        jButtonDeleteCar = new javax.swing.JButton();
        jScrollAreaCars = new javax.swing.JScrollPane();
        jTableCars = new javax.swing.JTable();
        customersManager = new javax.swing.JDialog();
        jButtonCustomersDone = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        customersMenuItem = new javax.swing.JMenuItem();
        carMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jMenuData = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        carManagerGui.setTitle("Car Management");
        carManagerGui.setModal(true);

        jButtonDone.setText("done");
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jButtonAddCar.setText("add");
        jButtonAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCarActionPerformed(evt);
            }
        });

        jButtonDeleteCar.setText("delete");
        jButtonDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCarActionPerformed(evt);
            }
        });

        CarTableModel carModel = new CarTableModel();
        jTableCars.setModel(carModel
        );
        jScrollAreaCars.setViewportView(jTableCars);

        javax.swing.GroupLayout carManagerGuiLayout = new javax.swing.GroupLayout(carManagerGui.getContentPane());
        carManagerGui.getContentPane().setLayout(carManagerGuiLayout);
        carManagerGuiLayout.setHorizontalGroup(
            carManagerGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carManagerGuiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddCar)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeleteCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDone)
                .addGap(19, 19, 19))
            .addComponent(jScrollAreaCars, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        carManagerGuiLayout.setVerticalGroup(
            carManagerGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carManagerGuiLayout.createSequentialGroup()
                .addComponent(jScrollAreaCars, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carManagerGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDone)
                    .addComponent(jButtonAddCar)
                    .addComponent(jButtonDeleteCar)))
        );

        customersManager.setTitle("Customers Managemnt");
        customersManager.setModal(true);

        jButtonCustomersDone.setText("done");
        jButtonCustomersDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomersDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customersManagerLayout = new javax.swing.GroupLayout(customersManager.getContentPane());
        customersManager.getContentPane().setLayout(customersManagerLayout);
        customersManagerLayout.setHorizontalGroup(
            customersManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersManagerLayout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jButtonCustomersDone)
                .addContainerGap())
        );
        customersManagerLayout.setVerticalGroup(
            customersManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersManagerLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jButtonCustomersDone)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Basic data");

        customersMenuItem.setMnemonic('t');
        customersMenuItem.setText("Customers ");
        customersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(customersMenuItem);

        carMenuItem.setMnemonic('y');
        carMenuItem.setText("Cars");
        carMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(carMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Bookings");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Complaints");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        jMenuData.setText("Data");

        jMenuItem1.setText("Grading(Noten)");
        jMenuData.add(jMenuItem1);

        jMenuItem2.setText("Semesterchange");
        jMenuData.add(jMenuItem2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Internship");
        jMenuData.add(jCheckBoxMenuItem1);

        menuBar.add(jMenuData);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        Car.saveCars();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void carMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carMenuItemActionPerformed
        carManagerGui.setVisible(true);
    }//GEN-LAST:event_carMenuItemActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        carManagerGui.setVisible(false);
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void jButtonAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCarActionPerformed
        // create an empty new "fake" car
        // ask the car manager to make an empty car
        Car newCar = carManager.createCar();
        // insert the new car into our data store so that user will see it
        CarTableModel carTable = (CarTableModel) jTableCars.getModel();
        carTable.addRow(newCar);  // adds the new car in last row
        // select last row so that user will see it
        jTableCars.changeSelection(carTable.getRowCount() - 1, 0, false, false);
    }//GEN-LAST:event_jButtonAddCarActionPerformed

    private void jButtonDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCarActionPerformed
        int selectedRowIndex = jTableCars.getSelectedRow();
        if (selectedRowIndex < 0)
        { // no row is selected!
            new JOptionPane().showMessageDialog(carManagerGui, "select a car first!", "Hint:", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Get data from selected row and ask if user really wants to delete it
        CarTableModel carTable = (CarTableModel) jTableCars.getModel();
        int selectedID = (int) carTable.getValueAt(selectedRowIndex, 0);
        String selectedDescription = "ID: " + selectedID + " \r\n" + (String) carTable.getValueAt(selectedRowIndex, 1);
        int answer = new JOptionPane().showConfirmDialog(carManagerGui, selectedDescription, "Delete this car?", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION)
        {  //User really wants to delete the car
            carTable.deleteRow(selectedRowIndex);
            // select the row again, but at most the last row  (This is rowcount -1! 
            selectedRowIndex = Math.min(selectedRowIndex, carTable.getRowCount() - 1);
            jTableCars.changeSelection(selectedRowIndex, 0, false, false);
        }
    }//GEN-LAST:event_jButtonDeleteCarActionPerformed

    private void jButtonCustomersDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomersDoneActionPerformed
        customersManager.setVisible(false);
    }//GEN-LAST:event_jButtonCustomersDoneActionPerformed

    private void customersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersMenuItemActionPerformed
        customersManager.setVisible(true);
    }//GEN-LAST:event_customersMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Car.saveCars();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CarGuiExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CarGuiExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CarGuiExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CarGuiExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CarGuiExample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDialog carManagerGui;
    private javax.swing.JMenuItem carMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JDialog customersManager;
    private javax.swing.JMenuItem customersMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButtonAddCar;
    private javax.swing.JButton jButtonCustomersDone;
    private javax.swing.JButton jButtonDeleteCar;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollAreaCars;
    private javax.swing.JTable jTableCars;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
